name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Prepare deployment package
        run: |
          # Create a temp directory for combined deployment
          mkdir -p deployment

          # Copy backend files
          cp -r backend/* deployment/

          # Ensure the frontend/dist directory exists relative to backend
          mkdir -p deployment/frontend
          cp -r frontend/dist deployment/frontend/

          # Copy web.config for SPA routing if exists
          cp frontend/web.config deployment/frontend/dist/ || true

          # Create a routes.json file for Static Web Apps routing
          echo '{ "routes": [{ "route": "/api/*", "methods": ["GET", "POST", "PUT", "DELETE"], "rewrite": "/api/$1" }, { "route": "/*", "serve": "/frontend/dist/index.html", "statusCode": 200 }] }' > deployment/staticwebapp.config.json

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_ROCK_04279250F }}
          action: "upload"
          app_location: "./deployment"
          api_location: ""
          output_location: ""
          skip_app_build: true
          skip_api_build: true
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_ROCK_04279250F }}
          action: "close"
          app_location: "./deployment"
