name: Build and deploy Node.js app to Azure Web App - GKM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Instalacja Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Sprawdzenie plików package.json
      - name: Check frontend package.json
        run: |
          cd frontend
          ls -la
          cat package.json

      - name: Check backend package.json
        run: |
          cd backend
          ls -la
          cat package.json

      # Instalacja zależności frontendu
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm run build --if-present

      # Instalacja zależności backendu
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
          npm run build --if-present

      # Lista plików w folderze frontend przed kopiowaniem
      - name: List files in frontend directory
        run: ls -R frontend

      # Lista plików w folderze backend przed kopiowaniem
      - name: List files in backend directory
        run: ls -R backend

      # Tworzenie paczki dla wdrożenia
      - name: Zip artifact for deployment
        run: |
          mkdir release
          # Sprawdzenie, czy są pliki wynikowe w folderze frontend
          if [ -d "frontend/dist" ]; then
            cp -r frontend/dist release/frontend
          fi
          # Sprawdzenie, czy są pliki wynikowe w folderze backend
          if [ -d "backend/dist" ]; then
            cp -r backend/dist release/backend
          fi
          # Zarchiwizowanie paczki
          zip -r release.zip release

      # Przekazanie paczki dla zadania wdrożenia
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      # Pobranie artefaktu z zadania build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Rozpakowanie artefaktu przed wdrożeniem
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Sprawdzenie plików po rozpakowaniu
      - name: Check files after unzipping
        run: |
          ls -R release

      # Logowanie do Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_92E1CF6DB3E9420E8E88E5EFC9F2D6F4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3F72622A46E54F59BF3AD025D669D014 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7997B80151FC40D4A5802EDCF15DA769 }}

      # Wdrożenie na Azure Web App
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "GKM" # Zmień na nazwę swojej aplikacji na Azure
          slot-name: "Production"
          package: "./release" # Używamy paczki z frontendem i backendem
