name: Build and Deploy Node.js App to Azure Web App - GKM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Install Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd ./frontend
          npm install

      # Build frontend
      - name: Build frontend
        run: |
          cd ./frontend
          npm run build

      # Install backend dependencies (no build)
      - name: Install backend dependencies
        run: |
          cd ./backend
          npm install

      # Prepare files for deployment
      - name: Prepare files for deployment
        run: |
          mkdir -p release
          # Copy frontend build files if they exist
          if [ -d "frontend/dist" ]; then
            cp -r frontend/dist release/frontend
          else
            echo "Frontend build directory not found!"
          fi
          # Copy backend files directly (no build)
          if [ -d "backend" ]; then
            cp -r backend release/backend
          else
            echo "Backend directory not found!"
          fi
          # Copy the start.sh file if it exists
          if [ -f "start.sh" ]; then
            cp start.sh release/
          else
            echo "start.sh not found!"
          fi
          # Archive the files into a zip
          zip -r release.zip release

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-artifact
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-artifact

      # Unzip the artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "GKM"
          slot-name: "Production"
          package: "./release"
