name: Build and deploy Node.js app to Azure Web App - GKM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd /home/site/wwwroot/frontend
          npm install

      # Build frontend
      - name: Build frontend
        run: |
          cd /home/site/wwwroot/frontend
          npm run build

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd /home/site/wwwroot/backend
          npm install

      # Prepare files for deployment
      - name: Prepare files for deployment
        run: |
          mkdir /home/site/wwwroot/release
          # Move frontend build files
          if [ -d "/home/site/wwwroot/frontend/dist" ]; then
            cp -r /home/site/wwwroot/frontend/dist /home/site/wwwroot/release/frontend
          fi
          # Move backend build files (assuming backend uses dist as well)
          if [ -d "/home/site/wwwroot/backend/dist" ]; then
            cp -r /home/site/wwwroot/backend/dist /home/site/wwwroot/release/backend
          fi
          # Copy start.sh script
          cp /home/site/wwwroot/start.sh /home/site/wwwroot/release/
          # Archive the release folder
          zip -r /home/site/wwwroot/release.zip /home/site/wwwroot/release

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: /home/site/wwwroot/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip artifact before deployment
      - name: Unzip artifact for deployment
        run: unzip /home/site/wwwroot/release.zip -d /home/site/wwwroot/

      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_92E1CF6DB3E9420E8E88E5EFC9F2D6F4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3F72622A46E54F59BF3AD025D669D014 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7997B80151FC40D4A5802EDCF15DA769 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "GKM"
          slot-name: "Production"
          package: "/home/site/wwwroot/release"
